name: Deploy to AWS ECS

on:
  push:
    branches:
      - main # Se ejecuta automáticamente cuando haces push a la rama main

env:
  AWS_REGION: us-east-1                   # Cambia por tu región de AWS
  ECR_REPOSITORY: mi-microservicio-java   # Nombre de tu repositorio en AWS ECR
  ECS_SERVICE: subcripciones-service      # Nombre de tu servicio en AWS ECS
  ECS_CLUSTER: devops-cluster             # Nombre de tu clúster en AWS ECS
  ECS_TASK_DEFINITION: task-definition.json # Archivo de definición de tarea

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configurar Java para validar que compile bien antes de armar el Docker
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Autenticación segura en AWS usando credenciales guardadas secretamente
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Iniciar sesión en el registro de contenedores de AWS
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Compilar, etiquetar y subir la imagen a AWS ECR
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }} # Usa el ID del commit como versión única
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./subcripciones
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Actualizar la definición de la tarea en ECS con la nueva imagen
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: microservice-java
          image: ${{ steps.build-image.outputs.image }}

      # Desplegar en AWS ECS Fargate
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true